CREATE DATABASE INVOICE;
use INVOICE;
SHOW DATABASES;
create table student(id int primary key auto_increment,name varchar(20),age int,city varchar(30);
INSERT INTO student VALUES('MCA001','ammu');
INSERT INTO student VALUES('MCA002','manu');
INSERT INTO student VALUES('MCA003','achu');
desc student; 
SELECT*fROM student;
ALTER TABLE student add dob date;
desc student;
 select*from student;
ALTER TABLE student modify dob year;
desc student;
ALTER TABLE student drop city;
desc student; 
create table CUSTOMER(cust_id int primary key auto_increment,address varchar(30),city varchar(20),ph_no int);
create table PRODUCT(p_id int primary key auto_increment,pname varchar(30),price int default'0');
desc CUSTOMER;
desc PRODUCT;
alter table CUSTOMER add name varchar(20);
desc CUSTOMER;
create table INVOICE_MASTER(inv_id int primary key auto_increment,cust_id int,constraint cust_id foreign key(cust_id)references CUSTOMER(cust_id),inv_date date);
desc INVOICE_MASTER;
create table INVOICE_ITEM(inv_id int,constraint inv_id foreign key(inv_id)7 references INVOICE_MASTER(inv_id),p_id int,constraint P_id foreign key(p_id)references PRODUCT(p_id),quantity int);
desc INVOICE_ITEM;
show tables;